import { EffectFn, Spell } from './index';
import * as Unit from '../entity/Unit';
import { Vec2 } from '../jmath/Vec';
import { IImageAnimated } from '../graphics/Image';
import Underworld from '../Underworld';
export declare const clone_id = "clone";
declare const spell: Spell;
export declare function cloneEffect(addClonesToTargetArray: boolean): EffectFn;
export declare function doCloneUnit(unit: Unit.IUnit, underworld: Underworld, prediction: boolean, summoner: Unit.IUnit, spawnLocation: Vec2 | undefined): Unit.IUnit | undefined;
export declare function animateMitosis(image?: IImageAnimated): Promise<void>;
export default spell;
