declare const mapping: {
    showWalkRope: string[];
    dequeueSpell: string[];
    openInventory: string[];
    ping: string[];
    recenterCamera: string[];
    endTurn: string[];
    spell1: string[];
    spell2: string[];
    spell3: string[];
    spell4: string[];
    spell5: string[];
    spell6: string[];
    spell7: string[];
    spell8: string[];
    spell9: string[];
    spellLeft1: string[];
    spellLeft2: string[];
    spellLeft3: string[];
    spellLeft4: string[];
    spellLeft5: string[];
    spellLeft6: string[];
    spellLeft7: string[];
    spellLeft8: string[];
    spellLeft9: string[];
    spellRight1: string[];
    spellRight2: string[];
    spellRight3: string[];
    spellRight4: string[];
    spellRight5: string[];
    spellRight6: string[];
    spellRight7: string[];
    spellRight8: string[];
    spellRight9: string[];
    cameraUp: string[];
    cameraDown: string[];
    cameraLeft: string[];
    cameraRight: string[];
    touchPadMoveCharacter: string[];
    openChat: string[];
};
export default mapping;
export declare function fullyUpdateControls(newMapping: any): void;
export declare function keyToHumanReadable(keyboardKeys: string[]): string;
interface ModifierKeys {
    ctrlKey: boolean;
    shiftKey: boolean;
    altKey: boolean;
}
export declare function getKeyCodeMapping(keyCode: string, modifierKeys?: ModifierKeys): string | undefined;
