declare const originalMapping: Readonly<{
    showWalkRope: string[];
    dequeueSpell: string[];
    openInventory: string[];
    ping: string[];
    recenterCamera: string[];
    endTurn: string[];
    cameraUp: string[];
    cameraDown: string[];
    cameraLeft: string[];
    cameraRight: string[];
    touchPadMoveCharacter: string[];
    openChat: string[];
    adminPowerBar: string[];
    discardCards: string[];
    spell1: string[];
    spell2: string[];
    spell3: string[];
    spell4: string[];
    spell5: string[];
    spell6: string[];
    spell7: string[];
    spell8: string[];
    spell9: string[];
    spellLeft1: string[];
    spellLeft2: string[];
    spellLeft3: string[];
    spellLeft4: string[];
    spellLeft5: string[];
    spellLeft6: string[];
    spellLeft7: string[];
    spellLeft8: string[];
    spellLeft9: string[];
    spellLeft1b: never[];
    spellLeft2b: never[];
    spellLeft3b: never[];
    spellLeft4b: never[];
    spellLeft5b: never[];
    spellLeft6b: never[];
    spellLeft7b: never[];
    spellLeft8b: never[];
    spellLeft9b: never[];
    spellLeft1c: never[];
    spellLeft2c: never[];
    spellLeft3c: never[];
    spellLeft4c: never[];
    spellLeft5c: never[];
    spellLeft6c: never[];
    spellLeft7c: never[];
    spellLeft8c: never[];
    spellLeft9c: never[];
    spellRight1: string[];
    spellRight2: string[];
    spellRight3: string[];
    spellRight4: string[];
    spellRight5: string[];
    spellRight6: string[];
    spellRight7: string[];
    spellRight8: string[];
    spellRight9: string[];
    spellRight1b: never[];
    spellRight2b: never[];
    spellRight3b: never[];
    spellRight4b: never[];
    spellRight5b: never[];
    spellRight6b: never[];
    spellRight7b: never[];
    spellRight8b: never[];
    spellRight9b: never[];
    spellRight1c: never[];
    spellRight2c: never[];
    spellRight3c: never[];
    spellRight4c: never[];
    spellRight5c: never[];
    spellRight6c: never[];
    spellRight7c: never[];
    spellRight8c: never[];
    spellRight9c: never[];
}>;
export default originalMapping;
export declare function fullyUpdateControls(newMapping: any): void;
export declare function keyToHumanReadable(keyboardKeys: string[]): string;
interface ModifierKeys {
    ctrlKey: boolean;
    shiftKey: boolean;
    altKey: boolean;
}
export declare function getKeyCodeMapping(keyCode: string, modifierKeys?: ModifierKeys): string | undefined;
