import * as AnimationCombos from './graphics/AnimationCombos';
import * as FloatingText from './graphics/FloatingText';
import * as JImage from './graphics/Image';
import * as ImmediateModeSprites from './graphics/ImmediateModeSprites';
import * as JpromptAll from './graphics/Jprompt';
import * as ParticleCollection from './graphics/ParticleCollection';
import * as Particles from './graphics/Particles';
import * as PixiUtils from './graphics/PixiUtils';
import * as PlanningView from './graphics/PlanningView';
import * as CardUI from './graphics/ui/CardUI';
import * as colors from './graphics/ui/colors';
import * as colorUtil from './graphics/ui/colorUtil';
import * as eventListeners from './graphics/ui/eventListeners';
import * as keyMapping from './graphics/ui/keyMapping';
import * as JAudio from './Audio';
declare const SpellmasonsAPIFrontend: {
    AnimationCombos: typeof AnimationCombos;
    FloatingText: typeof FloatingText;
    JImage: typeof JImage;
    ImmediateModeSprites: typeof ImmediateModeSprites;
    JpromptAll: typeof JpromptAll;
    ParticleCollection: typeof ParticleCollection;
    Particles: typeof Particles;
    PixiUtils: typeof PixiUtils;
    PlanningView: typeof PlanningView;
    CardUI: typeof CardUI;
    colors: typeof colors;
    colorUtil: typeof colorUtil;
    eventListeners: typeof eventListeners;
    keyMapping: typeof keyMapping;
    JAudio: typeof JAudio;
};
export default SpellmasonsAPIFrontend;
