export declare const RIGHT_CLICK_DOUBLE_MS_THRESHOLD = 500;
export declare const RIGHT_CLICK_DOUBLE_DISTANCE_THRESHOLD = 30;
export declare const PLAYER_BASE_HEALTH = 40;
export declare const UNIT_MOVE_SPEED = 0.15;
export declare const COLLISION_MESH_RADIUS = 32;
export declare const UNIT_SIZE_RADIUS: number;
export declare const SELECTABLE_RADIUS = 36;
export declare const HEALTH_BAR_UI_Y_POS = 30;
export declare const UNIT_UI_BAR_HEIGHT = 5;
export declare const UNIT_UI_BAR_WIDTH = 34;
export declare const LOB_PROJECTILE_SPEED = 600;
export declare const UNIT_SIZE: number;
export declare const UNIT_BASE_HEALTH = 40;
export declare const UNIT_BASE_MANA = 60;
export declare const UNIT_BASE_STAMINA = 300;
export declare const PLAYER_BASE_ATTACK_RANGE: number;
export declare const PLAYER_BASE_STAMINA: number;
export declare const UNIT_BASE_DAMAGE = 30;
export declare const NON_HEAVY_UNIT_SCALE = 1;
export declare const STARTING_CARD_COUNT = 3;
export declare const OBSTACLE_SIZE: number;
export declare const MAX_PLAYERS = 8;
export declare const NUMBER_OF_TOOLBAR_SLOTS = 9;
export declare const NUMBER_OF_EXTRA_TOOLBAR_SLOTS = 9;
export declare const UNIT_MINIBOSS_HEALTH_MULTIPLIER = 3;
export declare const UNIT_MINIBOSS_SCALE_MULTIPLIER = 1.7;
export declare const UNIT_MINIBOSS_DAMAGE_MULTIPLIER = 2;
export declare const MANA_GET_PER_TURN = 10;
export declare const UNIT_BASE_RADIUS: number;
export declare const CAMERA_BASE_SPEED = 20;
export declare const DEFAULT_ANIMATION_SPEED = 0.132;
export declare const CAST_RANGE_COYOTE_MARGIN = 25;
export declare const NAME_TEXT_ID = "nameText";
export declare const NAME_TEXT_DEFAULT_SIZE = 20;
export declare const NAME_TEXT_Y_OFFSET = 20;
export declare const LIQUID_X_SCROLL_SPEED = 400;
export declare const LIQUID_DISPLACEMENT_SPEED = 0.1;
export declare const LIQUID_DISPLACEMENT_SCALE = 0.6;
export declare const PIXI_TEXT_DROP_SHADOW: {
    dropShadow: boolean;
    dropShadowDistance: number;
};
export declare const NUMBER_OF_PLAYERS_BEFORE_BUDGET_INCREASES = 3;
export declare const LAST_LEVEL_INDEX = 11;
