import { UnitSource } from './index';
import { Faction } from '../../types/commonTypes';
import Underworld from '../../Underworld';
import * as Pickup from '../Pickup';
export declare const bossmasonUnitId = "Deathmason";
declare const deathmason: UnitSource;
export declare function summonUnitAtPickup(faction: Faction, pickup: Pickup.IPickup, underworld: Underworld): void;
export declare const ORIGINAL_DEATHMASON_DEATH = "ORIGINAL_DEATHMASON_DEATH";
export declare function registerDeathmasonEvents(): void;
export default deathmason;
